

server:
  port: 1004

spring:
  application:
    name: discovery hi
eureka:
  client:
    #    axios ?????? true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.18:8761/eureka